version: '3'

services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2021!"
      MYSQL_DATABASE: "captive"
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backend

networks: 
  backend:
    driver: bridge 